version: "3.5"

services:
  db:
    image: postgres:16-alpine3.19
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./schema.postgres.sql:/docker-entrypoint-initdb.d/schema.postgres.sql
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "rinha",
          "-U",
          "admin",
          "-h",
          "localhost",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: "160MB"
    networks:
      - rinha_network
  api01: &api
    image: matheusjv11/api-rinha-q1-2024:latest
    hostname: api01
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy # Wait for the database service to be healthy
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "180MB"
    networks:
      - rinha_network
  api02:
    <<: *api
    hostname: api02
    ports:
      - "8082:8080"
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "30MB"
    networks:
      - rinha_network
networks:
  rinha_network:
    driver: bridge
