version: "3.5"

services:
  db:
    image: postgres:16-alpine3.19
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./src/shared/infra/database/postgres/schema.postgres.sql:/docker-entrypoint-initdb.d/schema.postgres.sql
    deploy:
      resources:
        limits:
          cpus: "0.13"
          memory: "140MB"
networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
